version: '3.7'

services:
  web:
    image: "mysite:dev"

    build:
      target: development_build
      context: .
      dockerfile: ./Dockerfile
      args:
        DJANGO_ENV: development
    command: python -Wd manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./config/.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/.env.dev
  

volumes:
  postgres_data: